price_group:
  name:
    base: 'Base Rate'
    external: 'External Rate'
    cancer_center: 'Cancer Center Rate'

financial:
  # in the format MM-DD
  fiscal_year_begins: 09-01

validator:
  class_name: ValidatorDefault
  test:
    factory: # relative to Rails.root
    helper: 'spec/validator_helper' # relative to Rails.root

email:
  from: 'noreply@example.com'
  fake:
    enabled: false
    to:
  exceptions:
    sender: 'noreply@example.com'
    recipients: [ 'warn@example.com', 'error@example.com' ]