validator:
  class_name: ValidatorDefault
  test:
    factory: # relative to Rails.root
    helper: 'spec/validator_helper' # relative to Rails.root

email:
  from: 'noreply@example.com'
  fake:
    enabled: false
    to:
  exceptions:
    sender: 'noreply@example.com'
    recipients: [ 'warn@example.com', 'error@example.com' ]