price_group:
  name:
    base: 'Base Rate'
    external: 'External Rate'
    cancer_center: 'Cancer Center Rate'

financial:
  # in the format MM-DD
  fiscal_year_begins: 09-01

validator:
  class_name: ValidatorDefault
  test:
    factory: # relative to Rails.root
    helper: 'spec/validator_helper' # relative to Rails.root

email:
  from: 'noreply@example.com'
  fake:
    enabled: false
    to:
  exceptions:
    sender: 'noreply@example.com'
    recipients: [ 'warn@example.com', 'error@example.com' ]

billing:
  review_period: <%= 7.days %>

#
# For these settings use SettingsHelper#feature_on?
feature:
  create_users_on: true
  password_update_on: true
  recharge_accounts_on: true
  expense_accounts_on: true
  edit_accounts_on: true
  suspend_accounts_on: true
